name: '${name}'
version: '${version}'
api-version: '1.16'

main: '${group}.UntitledLibPlugin'

commands:
  markdown:
    aliases: [ 'md' ]
    usage: '/markdown'
    permission: 'untitledlib.markdown'
