name: '${name}'
version: '${version}'
api-version: '1.16'

main: '${group}.lib.plugin.UntitledLibPlugin'

commands:
  markdown:
    aliases: [ 'md' ]
    usage: '/markdown'
    permission: 'untitledlib.markdown'

  config:
    aliases: [ 'cfg' ]
    usage: '/config <plugin> <update | save | reload> [<setting> <value>]'
    permission: 'untitledlib.config'
